### ISSUE TITLE
Can no longer get to MessageEase layout

### ISSUE THREAD

**Issue by jfmcbrayer** [dessalines/thumb-key#146] opened 2023-04-13 21:25 UTC
Since a while, every time Thumb-Key updates, my layout gets changed away from MessageEase, probably to whatever had the same index in the list of layouts? So far that hasn't been a problem, I just switch it back. This time, I haven't been able to reach the layout I want. I'm attaching an image to show the problem. There doesn't seem to be any way to scroll down, and it looks like whatever the next layout in the list is, is showing its check box but not its label.

![Screenshot_20230413-171110_Thumb-Key](https://user-images.githubusercontent.com/632733/231885845-9272d1b8-d5e5-4a1f-b9b8-84682abe8a68.png)

This is on LineageOS 20 on a Moto G7.

**Comment by dessalines** [comment] 2023-04-13 21:50
Dupe of #130

**Closed by dessalines** 2023-04-13 21:50 UTC
