### ISSUE TITLE
Two handed layout doesn't have capslock

### ISSUE THREAD

**Issue by Kommynct** [dessalines/thumb-key#518] opened 2023-10-18 21:20 UTC
This strikes me as something that should be global, if not, I intend to make a version with symbols, and will fix it when I do. 

Swipe up on A twice with two handed mode to reproduce.

**Comment by alerque** [comment] 2023-10-19 12:55
Also missing from the two handed layout is a language toggle so you can get back to a different layout if you use more than one.

**Comment by dessalines** [comment] 2023-10-20 02:34
Dupe of #432

**Closed by dessalines** 2023-10-20 02:34 UTC
Labels: bug
