### ISSUE TITLE
Add button to change to other keyboard apps.

### ISSUE THREAD

**Issue by kcryptonian** [dessalines/thumb-key#380] opened 2023-09-03 02:27 UTC
- [ ] Did you check to see if this issue already exists?
- [ ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I'm tired of having to go to my phone settings everytime because I wanna change back to Gboard when I wanna type a loooong but emergency message coz I haven't gotten naturally used to thumbkey and would delay me alot to type such messages.
Include a "change input method" switch key. Thanks.

**Comment by penn5** [comment] 2023-09-04 09:19
Dupe of #379?

**Comment by dessalines** [comment] 2023-09-04 16:57
This is done, swipe left on the number key.

**Comment by penn5** [comment] 2023-09-04 17:33
I can't see a commit? 😅 
The issue is asking to support changing to other _apps_, not _layouts_

**Comment by dessalines** [comment] 2023-09-04 17:34
Oh other keyboard apps. Isn't that done through an android dropown from the notif bar?

**Comment by penn5** [comment] 2023-09-04 20:36
Yep that is possible, but it's more effort than a swipe left :)

**Closed** 2023-09-08 17:02 UTC
Labels: enhancement
