### ISSUE TITLE
Long-press for capital letters

### ISSUE THREAD

**Issue by dasnessie** [dessalines/thumb-key#362] opened 2023-08-24 04:48 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

MessageEase allows to swipe back and forth (or in a circle for the center letter of a key) to type a capital letter. This allows you to type faster, especially in languages that have a lot more capitals than English, where auto-capitalize doesn't help much (for example, German capitalizes every noun).

**Comment by nejni-marji** [comment] 2023-09-20 04:51
I'm thinking of implementing this. It should just be a matter of storing the furthest point from the start of a swipe and taking that as a middle point. That wouldn't work if your backswipe went too far, but I think that might be okay? If it isn't, I could check specifically for the first backwards change in magnitude?

**Comment by nejni-marji** [comment] 2023-09-20 05:02
Actually, I think something more robust like [gesture detection](https://developer.android.com/develop/ui/views/touch-and-input/gestures/detector) might be a better idea that trying to do it from scratch

**Comment by dasnessie** [comment] 2023-09-20 05:15
I'm not sure on the implementation details (I don't know anything about android development), but here's a short video of what my gestures look like on MessageEase: https://github.com/dessalines/thumb-key/assets/43586524/dc1b0f38-864e-46d0-a8b9-88935552e479

**Comment by nejni-marji** [comment] 2023-09-20 05:20
I think taking the furthest point from the start will work for swipes but I'm not sure how to handle circles in code yet.

**Comment by nejni-marji** [comment] 2023-09-20 06:18
I'm thinking of taking a sample of points and calculating the 1st and 2nd derivative of the angle with respect to time, and reversing that to check rotational continuity. I'll play with a toy example tomorrow and see what I can work out.

**Comment by nejni-marji** [comment] 2023-09-20 06:24
Wait, I missed something obvious. If I only do math at the end, I can get the center from the bounding box and check the radius at each sample. If the radius stays within a certain bound, it's round. That and a few other simpler checks should work.

**Comment by nejni-marji** [comment] 2023-09-20 06:35
In short:
- check for a consistent radius across samples
- check the change in angle is appropriate
- check the start and end are similar
Try to abort early if possible to save resources:
- bounding box is not close to square
- start and end are too far away

**Comment by robinmoussu** [comment] 2023-09-26 19:11
I’m very interested by this feature, it’s what I’m missing from MessagEase to migreate. And just to be sure that what you where planning to do matches what messagEase is able to do:
- 8 directions back-and-forth (using North, East, South and West notations + o for origin: o-N-o, o-NE-o, o-E-o, o-SE-o, o-S-o, o-SW-o, o-W-o, o-NW-o)
- 2 direction for circles (clockwise and anticlockwise)

I guess that some input system could use different variants, like
- 3 direction for back-and-forth (like o-NNE-o, o-S-o and o-NNW)
- knowing the starting point of the circle (clockwise + est will draw a circle bellow the starting point, or anticlockwise + north will draw a circle at the left of the starting point). This is what “8pen”, an alternative keyboard for android, uses.

I personally will not need those additional gesture, but I think that it could be nice to at least think of what need to be done to support it and leave a note for future implementer.

**Comment by Phidica** [comment] 2023-10-10 14:11
Duplicate of #317? I'm also keen to have this feature, but resigned to it never being implemented

**Comment by dessalines** [comment] 2023-12-01 16:11
Gonna close this for now, for these reasons:

- I'd prefer all actions, especially swipes, to be explicit and obvious. Adding hidden functionality isn't something I'd like here. Its already easy enough to go to shifted mode.
- Not all languages have capital letters, or a caps mode, meaning ...
- This would need to be a specific keyboard config. For languages like german, we could add a specific auto-capitalize setting, which would be far better than a hidden swipe functionality.

**Comment by BlueDrink9** [comment] 2024-02-07 01:18
I've seen you mention this stance through a few issues.

Have you articulated more in-depth anywhere else your reasoning for being so opposed to gestures and hidden features? it seems to me it's throwing a lot of functionality and ergonomics out with the bathwater, so to speak.
i feel like there should be strong reasons in order to justify a stance that leads to such a loss.

(not to mention, auto-caps often fails, as you can see in this message)

**Comment by Atn-D** [comment] 2024-02-07 01:23
@BlueDrink9 
now we have the @asdkant fork :
https://github.com/asdkant/open-thumb

**Comment by asdkant** [comment] 2024-02-07 12:55
> I've seen you mention this stance through a few issues.
> 
> Have you articulated more in-depth anywhere else your reasoning for being so opposed to gestures and hidden features? it seems to me it's throwing a lot of functionality and ergonomics out with the bathwater, so to speak. i feel like there should be strong reasons in order to justify a stance that leads to such a loss.
> 
> (not to mention, auto-caps often fails, as you can see in this message)
+1 to this, it's a UX discussion worth having. But at least, given the user base of this kind of keyboard, it'd be a good idea to have an explanation of this particular design choice in the README and referenced in the feature request form so people don't come again and again asking for stuff that is against the UX design goals of the project.

> @BlueDrink9 now we have the @asdkant fork : https://github.com/asdkant/open-thumb

As I've mentioned elsewhere, don't hold your breath on that one: I'm doing it on my spare time and I do DevOps, not app dev, so my coding experience is mostly in bash/python/etc. and small "run once and finish the job" stuff. I think it'll take me at least a span of a month (using spare time here and there) to get up to speed with Kotlin and Android app dev, after that I'll be able to implement meaningful change to the codebase. If a more experienced dev wants to help, it'll be more than welcome =)

**Comment by rommeswi** [comment] 2024-02-09 12:21
This is THE missing feature compared to messagease. I would not even need a proper circle motion just "back-and-forth" and "long press" would do it.

**Comment by robinmoussu** [comment] 2024-02-09 21:46
@asdkant I’m interested to help. Given that my energy is relatively low ATM I cannot guaranty anything, but I would like to try. I’m a dev, but android/kotlin are relatively unknown for me (I’m more of a C++/Rust guy). I tried to find how to build it from source (to eventually test my changes) and install it on my phone without success so far so any link to some docs is welcome.

**Comment by BlueDrink9** [comment] 2024-02-09 23:35
Android studio is how I got it to build

**Comment by dessalines** [comment] 2024-02-09 23:46
If its a simple long-press, I spose this would be fine.

**Comment by Atn-D** [comment] 2024-02-10 11:49
in MessageEase the longpress is used to enter digits

**Comment by asdkant** [comment] 2024-02-10 12:11
> in MessageEase the longpress is used to enter digits

yep, people coming from ME won't be happy.

i think being able to define at the keyboard level what long press does would be the better option

**Comment by rommeswi** [comment] 2024-02-10 12:39
I think the main issue is to avoid having to implement circular motion gestures. Defining these and adding configuration options for them is not straightforward. If we can get "long press" "long swipe" and perhaps even "return swipe", former ME users (like myself) will already be a lot happier.

**Comment by BlueDrink9** [comment] 2024-02-10 19:32
could be a setting to specify which layer the long press goes to. Every board has a main, shifted and numeric layer associated with it.

**Comment by Atn-D** [comment] 2024-02-12 01:13
this projet implement many gestures :
https://github.com/nightkr/flickboard

**Comment by dessalines** [comment] 2024-05-03 13:23
This is done by #854

**Closed by dessalines** 2024-05-03 13:23 UTC
