### ISSUE TITLE
Keyboard layout definitions as data (instead of code)

### ISSUE THREAD

**Issue by asdkant** [dessalines/thumb-key#657] opened 2024-02-04 19:55 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

As of now the keyboard layouts are defined as `.kt` files in the `app/src/main/java/com/dessalines/thumbkey/keyboards` folder of the repo. This may be fast from an application execution perspective, but it has some drawbacks:
- is not flexible (you need to build the whole app to test the layout definition)
- the syntax is not very ergonomic for someone that ONLY wants to write a keyboard layout

I think it would be better to have the keyboard layouts defined as data in something like JSON, YAML or TOML. Using a schema could help with validation and catching errors early.

Having this would, in the immediate term, make it easier for people who want to contribute with keyboard layouts.

In the medium-to-long term it would make it easier to implement the feature of user-defined keyboard layouts, with I'm fairly sure is something **A LOT** of users want.

**Comment by dessalines** [comment] 2024-02-04 21:15
Dupe of #645 , #586 , #351 , #290 , #160 .

I don't have time to add or maintain untyped / custom keyboard layouts. Every layout must pass a compile-time check.

**Closed by dessalines** 2024-02-04 21:15 UTC
Labels: enhancement

**Comment by asdkant** [comment] 2024-02-04 21:43
You don't **NEED** to maintain custom keyboard layouts. The point of taking those out of the source code is to make it so you don't have to. After that you can chuck them all to another repo and have someone else in charge of that, I'm sure there's at least one volunteer.

**Comment by dessalines** [comment] 2024-02-04 21:49
Someone's going to make sure they all pass checks by hand? What if we add a layout config option?

**Comment by asdkant** [comment] 2024-02-04 22:12
Checks can be automated, and whatever you use to parse the layout definition would have those checks. If you use a format with schema support, the tooling already exists so just have the validation in the schema.

JSON-schema in particular has kotlin implementations: https://json-schema.org/implementations#validators-kotlin

YAML also has some schema support: https://json-schema-everywhere.github.io/yaml (tho for kotlin stuff you'll want to turn it into JSON so unless you like YAML more than JSON it's kind of the same)


Would you be willing to accept a PR implementing this? I *REALLY* want custom keyboard layouts so I already got started on learning kotlin (already know how to code, just not in this lang) so I can implement that, and other stuff, for my own use.

**Comment by dessalines** [comment] 2024-02-04 23:07
No, I will not accept a PR adding un-typed / unchecked keyboards. You'll have to create a separate project if you want to maintain those and deal with all the potential run-time bugs.

We have over 90 keyboards now, showing that people haven't found it too difficult so far to copy-paste an existing layout.
