### ISSUE TITLE
Button to hide the keyboard

### ISSUE THREAD

**Issue by pulkomandy** [dessalines/thumb-key#678] opened 2024-02-06 12:31 UTC
### Describe your suggested feature

MessageEase has a button that allows to hide/close the keyboard. Since my phone is a bit small, this is rather useful sometimes to get the keyboard out of the way and see more of the display.

I can't find a way to do this in Thumb-Key. Is there already a way to close the keyboard? If so, can it be better documented? Or if not, can we add it somewhere?

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-02-06 17:35
You did not follow the instructions. Dupe of #668

**Closed by dessalines** 2024-02-06 17:35 UTC

**Comment by pulkomandy** [comment] 2024-02-06 17:43
> You did not follow the instructions. Dupe of #668 https://github.com/dessalines/thumb-key/issues/668 

The instructions says to look for *open* issues, and this one was already closed so I missed it. Sorry about that.

Anyways, the back button works for me, thanks! Maybe consider documenting that in the readme?

**Comment by dessalines** [comment] 2024-02-06 19:49
The back-button to hide keyboard is a standard on all keyboards and all android devices.
