### ISSUE TITLE
Clipboard upgrade

### ISSUE THREAD

**Issue by Speed5263** [dessalines/thumb-key#999] opened 2024-08-02 21:32 UTC
### Describe your suggested feature

okay so if you are familiar with the clipboard functionality of Gboard it allows for multiple text to be stored on the clipboard and then accessed and selected to be pasted now i wish for the same functionality i believe this can work and i absolutely love the concept of the keyboard even tho im still getting used to it i am looking forward for the implementation 

### Other details

nice job on the clown acknowledgement 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-08-03 16:33
I don't have time to add this, but if someone else wants to work on it, I'll re-open and assign it to them.

**Closed by dessalines** 2024-08-03 16:33 UTC

**Comment by Toldry** [comment] 2025-05-11 20:19
This appears to be a duplicate of #194
