### ISSUE TITLE
Different numpads for different layouts

### ISSUE THREAD

**Issue by dikey0ficial** [dessalines/thumb-key#779] opened 2024-02-29 20:27 UTC
### Describe your suggested feature

For example, they could contain national currency symbols.

My request is due to lack of "No." symbol (№), which is commonly used in Russian texts instead of "#"

### Other details

Thank you for such a nice keyboard! :)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-02-29 20:47
Dupe of #763 . 

Also if you'd like to add a cyrillic-specific numeric keyboard, feel free to create one and make a PR.

**Closed by dessalines** 2024-02-29 20:47 UTC

**Comment by dikey0ficial** [comment] 2024-03-01 10:46
Oh, okay, thought that issue requests another functionality :)
