### ISSUE TITLE
Custom buttons in unused space

### ISSUE THREAD

**Issue by thabubble** [dessalines/thumb-key#630] opened 2024-01-27 06:28 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
I have read some similar suggestions but not this exact one.

I have a lot of unused space around the keyboard. It would be nice to use that space. And a good use for it might be user-customizable buttons like cursor keys, modifier keys, etc.

**Comment by dessalines** [comment] 2024-01-28 16:31
Dupe of #586

**Closed by dessalines** 2024-01-28 16:31 UTC
Labels: enhancement
