### ISSUE TITLE
Return key doesn't start a new line in Discord

### ISSUE THREAD

**Issue by brendanlong** [dessalines/thumb-key#1076] opened 2024-09-22 22:24 UTC
### Steps to reproduce

1. Open the Discord app
2. Select the message input
3. Hit the return key in the bottom right of my keyboard

### Expected behavior

The input should move to the next line.

### Actual behavior

The first time I tried this, it sent the message I was typing.

Attempts to reproduce after that don't do anything.

Tapping and holding the return key works but is slow.

### version of the program

3.4.11

### Android version

Android 14

### Device

Google Pixel 9 Pro

### Other details

The return key works as expected in other apps.

Maybe related to #1065, something about sending slightly different than expected events?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-09-22 22:49
Dupe of #950 . Hold the enter button.

**Closed by dessalines** 2024-09-22 22:49 UTC
Labels: bug
