### ISSUE TITLE
Spacebar multi-tap broken since 2.6.8 in non-compose apps

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#625] opened 2024-01-24 10:13 UTC
**Thumb-Key Version**
2.6.8

**Describe the bug**
Spacebar multi-tap doesen't work in non-compose apps like GitHub, Aliucord or Telegram. it just sends more spaces.

**To Reproduce**
1. Go to one of the mentioned apps
2. Tap space twice
3. See 2 spaces even when multitap is enabled

**Comment by dessalines** [comment] 2024-01-24 14:04
Dupe of #242

**Closed by dessalines** 2024-01-24 14:04 UTC
Labels: bug

**Comment by KraXen72** [comment] 2024-01-24 14:33
this is a different issue imo. the original only happens under some specific circumstances when you move the cursor with your finger. this is about multitap not working at all in non-compose apps (it works in the thumb-key test field)

**Comment by dessalines** [comment] 2024-01-24 14:43
They're both related to the same thing, and its the same code that needs to be fixed.

**Comment by KraXen72** [comment] 2024-01-24 14:48
ah, okay
