### ISSUE TITLE
Hard to get diagonal up swipes in top row keys

### ISSUE THREAD

**Issue by DiegoLpVn** [dessalines/thumb-key#1041] opened 2024-09-02 15:44 UTC
### Steps to reproduce

1. Use any layout with letters or symbols in the up-right or up-left swipes of the top row. For example i tried with "thumb-key spanish symbols". 
2. Try to write those symbols. For example: £ € ª `

### Expected behavior

Doing and up-right or up-left swipe on any key of the top row should write the expected letter or symbol. 

### Actual behavior

It writes another symbol from the same key. 

### version of the program

3.4.5

### Android version

Android 12

### Device

Xiaomi Redmi Note 9 Pro

### Other details

I have tried with another layouts like the "english thumb-key symbols" or "english thumb-key programming" and I get the same problem. This only seems to happen to the top row (center and bottom row work without any problem). 
I also tried playing with the keys configuration (size, border, radius, padding) without seeing any improvement. 

May this have something to do with the fact that the keyboard top doesn't have enough space left to detect the swipe? I'm not sure what the problem is, it's just a guess.

I'll try with different devices as soon as I can to add more feedback. 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by DiegoLpVn** [comment] 2024-09-02 17:21
I have tried again a few times and sometimes it doesn't even work in other rows, or diagonal directions. Has anyone experienced this problem in other layouts?

**Comment by dessalines** [comment] 2024-09-02 17:25
Dupe of #937

**Closed by dessalines** 2024-09-02 17:25 UTC
Labels: bug
