### ISSUE TITLE
Left/right offset - similar to bottom offset

### ISSUE THREAD

**Issue by liberybell** [dessalines/thumb-key#957] opened 2024-06-26 04:17 UTC
### Describe your suggested feature

Just like the bottom offset allows to natch the keyboard a few or more pixels up, it would be great to have the option to natch the keyboard toward the left of the right a few pixels.
You see I am a lefty, so I have my thumb-key position to the left. But I have a hard time typing the corner symbols on the left squares since they are right on the edge of the phone. And with phone protector the situation is worse.
I am new to thumb-key, but I have been using msgease for over 20 years. Maybe there is some configuration I am overlooking?
Thanks!

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-06-28 19:37
Dupe of #783

**Closed by dessalines** 2024-06-28 19:37 UTC
