### ISSUE TITLE
Spanish layout

### ISSUE THREAD

**Issue by JdAriasb** [dessalines/thumb-key#168] opened 2023-04-18 04:08 UTC
I made a spanish layout file following the thumb-key guidelines.
[ThumbKeyESv1.zip](https://github.com/dessalines/thumb-key/files/11257753/ThumbKeyESv1.zip)

**Comment by dessalines** [comment] 2023-04-18 04:20
Dupe of #142

**Closed** 2023-04-18 04:20 UTC
Labels: enhancement
