### ISSUE TITLE
Drag-and-return to get a single uppercase letter

### ISSUE THREAD

**Issue by OldKrupnik** [dessalines/thumb-key#679] opened 2024-02-06 14:38 UTC
### Describe your suggested feature

First and foremost, I am a former user of messagease, and I am very happy that an opensource alternative can come to life, so thank you very much! 

I used another (quicker) way to capitalize letters frequently, other than the basic one (swipe up with the button next to #), it would be great if it were implemented.

So, to enter a single uppercase letter, instead of drag, we drag-and-return to get a single uppercase letter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
- [X] This is a **single** feature request,  in case of multiple feature requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I have written a short but informative title.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-02-06 17:30
You didn't follow the instructions above. Dupe of #648

**Closed by dessalines** 2024-02-06 17:30 UTC
