### ISSUE TITLE
Customize letters size?

### ISSUE THREAD

**Issue by alejoelmejor** [dessalines/thumb-key#884] opened 2024-05-07 21:30 UTC
### Describe your suggested feature

I'm recently into this kind of keyboards, not a long-time messagease user, and as I was adapting to the key layout, I found myself struggling to find letters that require a swipe, because they are so small on a keyboard. I think it would be useful, especially for beginners, to have sliders in settings which customize the size of central and side letters (or a single slider that changes their sizes proportionally to each other). What do you think?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-05-07 22:47
Dupe of #838

**Closed by dessalines** 2024-05-07 22:47 UTC
