### ISSUE TITLE
Holding down backspace should erase multiple characters.

### ISSUE THREAD

**Issue by MujtabaAsim** [dessalines/thumb-key#190] opened 2023-04-24 16:55 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

First of all, regarding my issue, whenever I click/hold the backspace key, it only removes the previous character. Removing a whole sentence at the moment feels like a chore. It would be really cool if it functioned more like a traditional keyboard and kept erasing while the button is held down.

Second, I really love this project and would like to build the appropriate skill set to contribute and help its development. Do you have any resources you could recommend me to get started?

**Comment by dessalines** [comment] 2023-04-25 00:25
Dupe of #48 

One reason I currently don't have tap-and-hold actions, is because they might slow down key taps. Currently you can swipe left to delete a whole word, which is much faster.

> Second, I really love this project and would like to build the appropriate skill set to contribute and help its development. Do you have any resources you could recommend me to get started?

Thanks!

You could learn [Jetpack-compose](https://developer.android.com/jetpack/compose), which is the preferred way to build android apps nowadays. It has lots of tutorials and resources in there.

**Closed by dessalines** 2023-04-25 00:25 UTC
Labels: enhancement
