### ISSUE TITLE
Pressing space bar multiple times in multiple apps only creates more spaces

### ISSUE THREAD

**Issue by nexiron** [dessalines/thumb-key#751] opened 2024-02-22 10:41 UTC
### Steps to reproduce

1. open any of the following apps:
- WhatsApp
- FairMail
- Samsung default Contacts app
- Samsung default Phone app

2. write a few letters
3. tap space multiple times for punctuation

### Expected behavior

Auto print characters (e.g., ,, ., !, etc.)

### Actual behavior

Spaces only (  ) are printed.

### version of the program

2.6.18

### Android version

Android 12

### Device

Samsung Galaxy S10

### Other details

Default Samsung OS installed with Thumb-Key from GitHub. 

#685 touches on the same issue but specifically only on Fennec. I am experiencing this issue on a number of apps. 

P.S. Although i read the acknowledgements I would like to be able to admit that I am a clown. Perhaps I will suggest this as a feature for the bug reporting form. 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by Lysalana** [comment] 2024-03-04 15:46
Have you tried checking the checkbox found under the Thumb-key menu >Behavior>Spacebar Multi-taps? Your steps in reproducing this 'bug' didn't contain this important step.

I tried reproducing the steps written in your issue and it works just as fine, except that I checked the Spacebar Multi-taps feature beforehand.

**Comment by sibelius1269** [comment] 2024-03-05 18:18
Hi. I also experience the same thing, and I've verified that I have that option activated.

**Comment by sibelius1269** [comment] 2024-03-05 18:24
I forgot to clarify that I use the Spanish keyboard versions 😅

**Comment by Lysalana** [comment] 2024-03-05 18:33
I also tried espanol messagease and espanol thumb-key, both also working fine for me with that option checked. Which Spanish keyboard are you using?

**Comment by sibelius1269** [comment] 2024-03-05 21:30
The same as you

**Comment by dessalines** [comment] 2024-03-08 16:18
This could be a jetpack compose version related issue: https://github.com/dessalines/thumb-key/issues/625

**Comment by bdtoole** [comment] 2024-03-15 18:11
Just adding here that I see the broken behavior on the latest 2.7 version in the following:
* ThumbKey test area
* Vivaldi web browser URL bar
* F-Droid app search field
* Play store app search field
* Slack app
* Google Messages app (within a text conversation)
* RedReader

I see the working behavior in the following:
* google.com search bar, accessed from Vivaldi web browser
* duckduckgo.com search bar, accessed from Vivaldi web browser
* github.com text fields, accessed from Vivaldi web browser
* Discord app
* Google Message app (within the New Conversation, To: field)

What's interesting to me is I found at least one app where it works in some areas but not in other areas within that app.

Device is a OnePlus 9 Pro.

**Comment by dessalines** [comment] 2024-03-22 18:21
I notice some different behavior, but not all of what you experience above with `2.7.0`. The thumb-key test area works fine, play store app field, and a few others.

**Comment by bdtoole** [comment] 2024-03-28 20:16
> I notice some different behavior, but not all of what you experience above with `2.7.0`. The thumb-key test area works fine, play store app field, and a few others.

Very strange. I've attempted clearing the cache, clearing application data, and doing a complete uninstall and re-install of the latest version and my behavior still persists. The fact that the test area is broken for me is particularly baffling.

I haven't tried a downgrade yet, but it looks like someone mentioned in #685 that the last working version for them was 2.6.6, so I'm thinking something must have changed with the 2.6.7 version that situationally broke this for folks.

**Comment by dessalines** [comment] 2024-03-29 13:26
I'd have to look at what we've added. Its also a little complicated because jetpack compose only recently added support for this checking, so its been half-broken for a long time.

**Comment by dessalines** [comment] 2024-05-03 13:35
Dupe of #685

**Closed by dessalines** 2024-05-03 13:35 UTC
Labels: bug
