### ISSUE TITLE
Hold 9 main keys plus space bar for numbers (MessageEase Keyboard feature)

### ISSUE THREAD

**Issue by PastTenseOfDraw** [dessalines/thumb-key#471] opened 2023-10-08 17:08 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

One option in MessageEase Keyboard that I found really valuable is being able to hold down one of the 9 main keys to get an input of 1 through 9 and space bar for 0.

I would appreciate this option being added to thumb-key.

**Comment by dessalines** [comment] 2023-10-08 23:24
Dupe of #403

**Closed by dessalines** 2023-10-08 23:24 UTC
Labels: enhancement
