### ISSUE TITLE
Macros FTW!!

### ISSUE THREAD

**Issue by quasipedia** [dessalines/thumb-key#664] opened 2024-02-05 01:13 UTC
Coming from MessageEase, I severely miss the macro functionality.  In MeassageEase this works by assigning string of text to a set of characters in the settings.  My typical usage pattern was for e-mails and addresses.

For example typing `@nl` would expand to `name.lastname@mailprovider.com`

**Comment by dessalines** [comment] 2024-02-05 02:07
Dupe of #162

Don't delete the issue questions please.

**Closed by dessalines** 2024-02-05 02:07 UTC
Labels: enhancement
