### ISSUE TITLE
moving the cursor does not reset spacebar multi-tap

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#242] opened 2023-05-24 13:30 UTC
**Thumb-Key Version**
1.3.0

**Describe the bug**
if you type space, move the cursor and type it again, it deletes the last letter and adds a comma. (i do not want to turn off spacebar multitaps, just want it to start from the beginnig of the character cycle if the cursor moves)

**To Steps to reproduce the behavior:**
| = cursor
1. type something like 'noproblem|'
2. realize misake, move cursor: 'no|problem'
3. hit space
4. move cursor: 'no problem|'
5. hitting space to continue typing instead produces 'no proble, |'

**Comment by dessalines** [comment] 2023-05-25 14:23
I can't replicate this for some reason.

**Comment by KraXen72** [comment] 2023-05-25 19:25
it seems to happen mostly when you grab the cursor by it's native android handle & move it. not that much when i move it with spacebar swipes

**Comment by dessalines** [comment] 2023-06-04 13:37
I think I *may* have found a fix for this one.

**Comment by dessalines** [comment] 2023-06-05 20:19
Not something I know how to do.

**Comment by KraXen72** [comment] 2023-06-06 02:06
this is what i mean:
![Screenshot_20230606-040457_GitHub.png](https://github.com/dessalines/thumb-key/assets/21956756/2adc4b34-091f-4cc1-9b85-237e14491c5c)

![Screenshot_20230606-040449_GitHub.png](https://github.com/dessalines/thumb-key/assets/21956756/3ed1fe0c-3008-4535-93b8-32de7971f37a)

**Comment by niccokunzmann** [comment] 2023-08-04 06:40
Another way to reproduce this is:

- type `123` space space
- (now, there should be `123, `)
- use the finger to set the cursor between 2 and 3
- tab space
- see `. 3, `

**Comment by 0xFOSSMan** [comment] 2023-09-05 17:24
> Another way to reproduce this is:
> 
>     * type `123` space space
> 
>     * (now, there should be `123, `)
> 
>     * use the finger to set the cursor between 2 and 3
> 
>     * tab space
> 
>     * see `. 3, `

tried reproducing it exactly like you said, didn't happen to me. Maybe it's fixed now?

**Comment by niccokunzmann** [comment] 2023-09-05 20:23
. 3, it depends on the input. When I do it in the test field in the thumbkey settings, it is not reproducible. In the text field of this email it was.

**Comment by 0xFOSSMan** [comment] 2023-09-05 23:30
, 3. oh yeah you are right it does. interesting.

Gesendet mit Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by KraXen72** [comment] 2023-09-20 21:58
as far as i can tell, this has been fixed by #401 or #424. I can no longer reproduce it! Can someone else try to reproduce it? Thanks!

**Comment by 0xFOSSMan** [comment] 2023-09-20 22:07
! 3.
can reproduce it in outlook.

Gesendet mit Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by KraXen72** [comment] 2023-09-20 22:24
ah okay. i was testing it in the thumb-key input box, and i forgot that it doesen't happen there.

**Comment by jm355** [comment] 2024-01-09 03:32
I don't know how to add a configurable tap timeout, but this works-ish. If you go fast enough you can still hit the error state, and if you wait too long you lose the double tap. That's fine for double tap but kind of sucks for triple tap. Maybe you could hack it even more such that the timeout only gets checked when tapCount == 1? 

```
diff --git a/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt b/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt
index 7b5e3ab..a1b4e66 100644
--- a/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt
+++ b/app/src/main/java/com/dessalines/thumbkey/ui/components/keyboard/KeyboardKey.kt
@@ -118,6 +118,7 @@ fun KeyboardKey(
     val releasedKey = remember { mutableStateOf<String?>(null) }
 
     var tapCount by remember { mutableIntStateOf(0) }
+    var timeOfLastTap by remember { mutableLongStateOf(0L) }
     val tapActions =
         if (spacebarMultiTaps) {
             buildTapActions(key)
@@ -180,12 +181,13 @@ fun KeyboardKey(
                 // Set the last key info, and the tap count
                 val cAction = key.center.action
                 lastAction.value?.let { lastAction ->
-                    if (lastAction == cAction) {
+                    if (lastAction == cAction && (System.currentTimeMillis() - timeOfLastTap) < 500) {
                         tapCount += 1
                     } else {
                         tapCount = 0
                     }
                 }
+                timeOfLastTap = System.currentTimeMillis()
                 lastAction.value = cAction
 
                 // Set the correct action
```

In researching this, I came across [InputConnection.requestCursorUpdates](https://developer.android.com/reference/android/view/inputmethod/InputConnection#requestCursorUpdates(int,%20int)). I believe you could call that with requestCursorUpdates([CURSOR_UPDATE_MONITOR](https://developer.android.com/reference/android/view/inputmethod/InputConnection#CURSOR_UPDATE_MONITOR), [CURSOR_UPDATE_FILTER_INSERTION_MARKER](https://developer.android.com/reference/android/view/inputmethod/InputConnection#CURSOR_UPDATE_FILTER_INSERTION_MARKER)), and implement [updateCursorAnchorInfo](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#updateCursorAnchorInfo(android.view.View,%20android.view.inputmethod.CursorAnchorInfo)) such that it would reset the tap count or something. That seems like the proper solution, but I couldn't figure out how to do that since I'm pretty unfamiliar with android dev. Anybody have any ideas?

**Comment by dessalines** [comment] 2024-01-09 16:51
> In researching this, I came across [InputConnection.requestCursorUpdates](https://developer.android.com/reference/android/view/inputmethod/InputConnection#requestCursorUpdates(int,%20int)). I believe you could call that with requestCursorUpdates([CURSOR_UPDATE_MONITOR](https://developer.android.com/reference/android/view/inputmethod/InputConnection#CURSOR_UPDATE_MONITOR), [CURSOR_UPDATE_FILTER_INSERTION_MARKER](https://developer.android.com/reference/android/view/inputmethod/InputConnection#CURSOR_UPDATE_FILTER_INSERTION_MARKER)), and implement [updateCursorAnchorInfo](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#updateCursorAnchorInfo(android.view.View,%20android.view.inputmethod.CursorAnchorInfo)) such that it would reset the tap count. That seems like the proper solution, but I couldn't figure out how to do that since I'm pretty unfamiliar with android dev. Anybody have any ideas or tips?

I tried this solution last weekend actually, but couldn't get it working. Its the right way to handle it, rather than a tap timeout. It needs someone other than me to take a crack at it.

**Comment by KraXen72** [comment] 2024-01-19 23:06
huge if true

**Comment by dessalines** [comment] 2024-01-21 18:32
Looks like this is still an issue on some text fields.

**Comment by jm355** [comment] 2024-01-21 18:39
Which ones? also there's a good chance the magic number of 15 that I used isn't ideal, or could be calculated based on the device, like pixel density of the screen or something

**Comment by dessalines** [comment] 2024-01-22 02:38
A lot of them: Signal, Markor, etc.

**Comment by jm355** [comment] 2024-01-22 03:01
what are you typing to reproduce it?

**Comment by dessalines** [comment] 2024-01-22 15:43
Its very inconsistent. Occasionally if I go to those text fields, spacebar multitap doesn't work at all. Then other times they work, but the move cursor doesn't that character replacing bug again.

**Comment by dessalines** [comment] 2024-11-21 02:37
The multitap now resets after a second now, so this should effectively be fixed.

**Closed by dessalines** 2024-11-21 02:37 UTC
Labels: bug
