### ISSUE TITLE
Import keyboard file

### ISSUE THREAD

**Issue by K0baU** [dessalines/thumb-key#545] opened 2023-11-02 18:04 UTC
- [ x ] Did you check to see if this issue already exists?
- [ x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
As keyboard layouts become more diverse, it'll be infeasible to have all keyboard files in this  repo in the future. If the app can import keyboard files from outside the repo, the benefit of this project will be much greater.

**Comment by dessalines** [comment] 2023-11-02 18:47
Dupe of #234

**Closed by dessalines** 2023-11-02 18:47 UTC
Labels: enhancement
