### ISSUE TITLE
Unable to update from 2.6.1 to 2.6.4 ("Package installer keeps stopping")

### ISSUE THREAD

**Issue by fuxoft** [dessalines/thumb-key#614] opened 2024-01-10 08:37 UTC
**Describe the bug**
F-Droid tells me that there is a new version of thumb-key available but trying to update it produces the error: "Package installer keeps stopping."
My phone is Pixel 6a with official ROM.

**To Reproduce**
1. Open F-Droid
2. Select "Thumb-Key"
3. Thumb-Key app page appears.
4. Click the "Update" blue button
5. In the dialog "Do you want to update this app?", select "Update"
6. Nothing happens, F-Droid goes back to step 3, Thumb-Key remains at version 2.6.1, blue "Update" button is still shown.
7. After repeating steps 3-6 a few times, the phone says "Package installer keeps stopping (App info / Close app)".

Other apps update correctly through F-Droid

**Comment by dessalines** [comment] 2024-01-10 14:26
Could be an issue with different signing keys, IE if you installed it via izzy/github, then try to update via f-droid, it might give you an error. Did you try uninstalling then reinstalling? 

BTW we're on v2.6.5 now.

**Comment by fuxoft** [comment] 2024-01-10 14:41
After uninstalling Thumb-Key, I am now unable to install it using F-Droid. The same problem as described above. Clicking "Install" key does nothing and after a few tries, I get a "Package installer keeps stopping" error.

So, what's the preferred method of installing Thumb-Key and (preferable) keeping it up to date automatically?

**Comment by fuxoft** [comment] 2024-01-10 14:58
UPDATE: I have added the Izzysoft repository to F-Droid and then tried installing Thumb-Key (2.6.6) from it. Same error as above. I have also completely reinstalled F-Droid, restarted my phone and tried again. Same error. Thumb-key cannot be installed.

Other random apps from F-Droid install without problem.

**Comment by fuxoft** [comment] 2024-01-10 15:09
UPDATE 2: Even when I manually download (using mobile browser) app-release.apk file for version 2.6.6 from GitHub, my phone is unable to install it and package manager silently crashes!

**Comment by dessalines** [comment] 2024-01-10 15:19
Could be a compose 1.5.7 issue on some devices. Could you try installing the apk in this tag? https://github.com/dessalines/thumb-key/releases/tag/2.6.5

**Comment by dessalines** [comment] 2024-01-10 15:30
Hrm... `2.6.1` is the only one that's working?

**Comment by fuxoft** [comment] 2024-01-10 15:36
No, I cannot install any of them, not even 2.6.1 (which I've used previously). Not from GitHub, not from F-Droid. I've also cleared all local files for "Package Manager". No change.

I've also tried to install 5 random apps from F-Droid. All of them install without problems.

**Comment by dessalines** [comment] 2024-01-10 15:45
Ugh... what a strange issue. The only things I can think of:

- App security related settings.
- ThumbKey was previously installed on the SDCard, and left some remnants preventing a new install.

I've never run into this one, and since I can't reproduce this myself, its going to be a hard one to figure out.

https://www.androiddata-recovery.com/blog/fix-app-not-installed-android

**Comment by dessalines** [comment] 2024-01-10 20:14
I've never tried this, but solution 4 from the top link: clear cache and data for the package installer app.

**Comment by fuxoft** [comment] 2024-01-10 20:19
Tried that. No change. :(

**Comment by dessalines** [comment] 2024-01-10 20:43
Apparently it can be due to a logo size on random phones: https://stackoverflow.com/questions/44255333/android-package-installer-keeps-stopping

But the current logo isn't even a picture, its an svg, and its also <500px.

**Comment by dessalines** [comment] 2024-01-10 20:48
I'll try to decrease them for the next release, but without an ADB log, I won't be able to figure this one out.

**Comment by fuxoft** [comment] 2024-01-10 20:52
I can try to get you the logs if you tell me what to do. I am not an Android ddeveloper, I don't use ADB but i am moderately computer proficient (I use Linux PCs exclusively for the last 15 years).

**Comment by dessalines** [comment] 2024-01-10 21:07
@fuxoft try running this apk, its with a lowered icon size. Besides that, I have no idea without logs.

[app-release.zip](https://github.com/dessalines/thumb-key/files/13894041/app-release.zip)

**Comment by fuxoft** [comment] 2024-01-10 22:48
oh my f**ing God, THAT ONE WORKS!!!

Except that icon looks really strange, like it shows only small part of it...

**Comment by dessalines** [comment] 2024-01-11 00:03
Really weird. Maybe has something to do with svg icons not being properly supported on some devices. bleh. I guess I'll close this for now then, the next release has that merged.

**Closed by dessalines** 2024-01-11 00:03 UTC
Labels: bug

**Comment by fuxoft** [comment] 2024-01-12 09:07
UPDATE: Yesterday, my phone received the standard Google firmware OTA. Package installer now doesn't crash but instead says "You can't install the app on your device" for older releases.

And here is how the app icon looks (for the latest, "correct", installable version):
![Screenshot_20240112-100234](https://github.com/dessalines/thumb-key/assets/6364775/2b4d231c-ec9b-4cc6-aa90-c862ab056f08)
