### ISSUE TITLE
Hitting enter in discord only hides keyboard

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#498] opened 2023-10-14 19:52 UTC
**Thumb-Key Version**
2.4.0

**Describe the bug**
Hitting enter in discord should make a new line, or worst-case, send the message (previous behaviour). Currently, just hides the keyboard without either sending the message or creating a new line. ENv4 layout.

**To Reproduce**
1. Go to Discord
2. Type a message
3. Hit enter

**Comment by jeremiah-miller** [comment] 2023-10-15 03:49
Same in signal and qksms for me

**Comment by nate2014jatc** [comment] 2023-10-15 21:34
Present in Discord Beta 200.12, Telegram 10.1.3 (3944), Signal 6.35.5, and Textra 4.68

**Comment by Matyeyev** [comment] 2023-10-16 16:58
it's happening on k9 mail too. how to repro:
open random mail, reply then type on first line. when you click enter it hiding keyboard and not go to next line.

**Comment by dessalines** [comment] 2023-10-16 20:53
Dupe of #136

**Closed by dessalines** 2023-10-16 20:53 UTC
Labels: bug

**Comment by nate2014jatc** [comment] 2023-10-16 20:56
You want new buggy behavior tracked under an old issue?

**Comment by storvik** [comment] 2023-10-16 21:39
Thx @dessalines, commit 57151aa9466699137a2adb9cc49642efb96213fa did fix issues introduced in 2.4.0 🎉
