### ISSUE TITLE
[Feature Request] Both Sides Option

### ISSUE THREAD

**Issue by JoshuaFern** [dessalines/thumb-key#226] opened 2023-05-16 05:36 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

I noticed that I have the choice between having the keyboard left, right, and centered. However, I'd like to have the keyboard on both sides so I can alternate keyboard entry with my thumbs. Not necessarily mirrored, but the same keyboard displayed twice with a gap in the middle, similar to the split option available on the iPad and other touchscreen keyboards.

**Comment by dessalines** [comment] 2023-05-16 13:07
Dupe of #178

**Closed by dessalines** 2023-05-16 13:07 UTC
Labels: enhancement
