### ISSUE TITLE
Gesture to enter numbers from letters view

### ISSUE THREAD

**Issue by nightkr** [dessalines/thumb-key#647] opened 2024-02-04 02:14 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

MessagEase lets you enter a number from the letters view by long-pressing the equivalent square. This does nothing in ThumbKey.

**Comment by dessalines** [comment] 2024-02-04 20:48
Dupe of #531

**Closed by dessalines** 2024-02-04 20:48 UTC
Labels: enhancement
