### ISSUE TITLE
Allow defining custom layouts.

### ISSUE THREAD

**Issue by matj1** [dessalines/thumb-key#1176] opened 2024-12-06 11:37 UTC
### Describe your suggested feature

I would like a way to customize layouts of Thumb-Key. An in-app interface would be nice, but editing text would work. The interface would allow creating, editing and sharing layouts without reinstalling the app. (If I understand it correctly, layouts are compiled into the app at this time.)

### Other details

I want a layout that is similar to a layout already present in Thumb-Key but with some changes, especially extra symbols. The layout menu already contains too many options, so I would not want that special layouts would be offered to everyone in the app. Loading layouts without compilation would mean that layouts could be quickly improved and shared without cluttering the layout menu.

Mentioning the interface, I imagined the interface in MessagEase, but that is janky, so I think that it needs to be better if it is added. Editing text seems easier to implement. The definitions in the source code are too verbose, but they could be done compactly in something like YAML.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-12-06 12:47
Dupe of #645 #234 #473 #160

**Closed by dessalines** 2024-12-06 12:47 UTC
