### ISSUE TITLE
Stretched display mode

### ISSUE THREAD

**Issue by Evengard** [dessalines/thumb-key#640] opened 2024-02-02 23:54 UTC
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Hello! There is 3 position modes: centered, left or right. I'm coming from MessagEase, and I'm actually using the "stretched" mode. Is it possible to implement it here as well?

Thanks!

**Comment by asdkant** [comment] 2024-02-04 02:10
What would "stretched" mode be?

**Comment by Evengard** [comment] 2024-02-04 08:13
![Screenshot_2024-02-04-11-12-22-80_984e1414ae90666a90f12ff17ec14a7f](https://github.com/dessalines/thumb-key/assets/798735/42e4ad78-ac03-49f4-8761-dc40c201935f)

That's how it is in the rival MessagEase

**Comment by dessalines** [comment] 2024-02-04 20:51
Dupe of #399

**Comment by Evengard** [comment] 2024-02-04 21:15
That's unfortunate. I'm really used to this stretched layout, and I think a lot of people too... Is there any reasoning behind WHY not planned to do a setting to make them not perfectly square?

**Comment by dessalines** [comment] 2024-02-04 21:18
Fluid layouts are more complicated (which keys are allowed to stretch and which aren't, where do they stretch?), or if you wanted to add h/w ratios for each key, it'd be much more complicated. If you do a PR for this tho I wouldn't be opposed, but it'd be a lot of work.

**Comment by Evengard** [comment] 2024-02-04 21:21
I am actually considering working on some PRs, so I want just to make sure we're on the same page.

In MessagEase in stretched mode actually all keys are stretched uniformely, without any regard to which key it is. I considered taking the same approach for that setting here. Do you think it is acceptable, or you have something different in mind?

**Comment by dessalines** [comment] 2024-02-04 21:25
Sure, that'd be fine. A boolean default off for `fill_width`

**Comment by Kommynct** [comment] 2024-02-05 00:45
It should also disable the button to move the keyboard to center/left/right if this is enabled.

**Comment by Evengard** [comment] 2024-02-05 01:11
Well that's debatable. I was actually thinking more along the lines of actually making it one of the settings (left, right, centered, **stretched [add]**). So that button would cycle through 4 of them instead of 3 current.

**Comment by Zwyx** [comment] 2024-02-05 02:39
Would also be super keen to have a stretch mode :+1: (Or the ability to change the keys' ratio to have them rectangular.)

**Comment by dessalines** [comment] 2024-02-17 16:28
Closed by the above PR

**Closed by dessalines** 2024-02-17 16:28 UTC
Labels: enhancement
