### ISSUE TITLE
F-Droid version is out of date (1.13.0)

### ISSUE THREAD

**Issue by fuxoft** [dessalines/thumb-key#452] opened 2023-10-02 07:58 UTC
When I click the "Get it on F-Droid" button here on GitHub, it leads me to f-droid.org page which offers the download of version 1.13.0 (which is missing the emoji key, Czech letter "ě" etc.) which was "added on 2023-09-06".

The version on izzysoft.de is 2.1.1.

**Comment by KraXen72** [comment] 2023-10-02 15:08
just an FYI, you can use the [Droid-ify](https://f-droid.org/en/packages/com.looker.droidify/) alternative client for F-Droid, which supports izzyOnDroid and other custom repos, has a nicer ui and fast & reliable updates. But i agree that the newest version should be on both repos, F-Droid and IzzyOnDroid

**Comment by Screwtapello** [comment] 2023-10-04 04:10
OK, 2.1.1 failed as well. I guess we wait.

**Comment by dessalines** [comment] 2023-10-04 12:32
Dupe of #400

**Closed by dessalines** 2023-10-04 12:32 UTC
Labels: bug
