### ISSUE TITLE
Numbers on letter long-press

### ISSUE THREAD

**Issue by Eletroboss** [dessalines/thumb-key#531] opened 2023-10-23 23:40 UTC
In MessagEase, one could type numbers by long-pressing the letter. However, this does not happen in ThumbKey and I can't find an option for it anywhere. This functionality would be very convenient if implemented, but I can see it wouldn't be a very high priority as one can simply press the "#" button.

**Comment by dessalines** [comment] 2023-10-24 01:22
Dupe of #310

**Closed by dessalines** 2023-10-24 01:22 UTC
Labels: enhancement
