### ISSUE TITLE
enable composed letters

### ISSUE THREAD

**Issue by rootsh0pf** [dessalines/thumb-key#204] opened 2023-05-04 06:55 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

I would love to be able to type composed characters like in MesseagEase: If I type "a" followed by "´" it gets combined to "á". Same for "`~¨^". This makes it very straight forward to enter some accented characters that are not directly on my layout, without switching layouts.

(btw: Thank you very much for this great new keyboard!)

**Comment by dessalines** [comment] 2023-05-04 22:11
There are also multitaps that you could potentially utilize for those diacritic characters. Check out the spacebar definition in `CommonKeys.kt` for an example of how to do those.

I think overall though, its better to have them as swipes off the main letter. 

Also, not every language needs every vowel+diacritic, which is why a lot of current language keyboards do have them already.

**Comment by mpice-mn** [comment] 2023-05-06 00:54
The problem is that letter positions change between the different language-specific keyboards, so it's not great for the muscle memory if you regularly type in multiple languages. I'd rather stick with one layout (e.g. English) and have the option for diacritics there. I now have both EN-programmer and EN-intl layouts active and I really like this setup so far.

But finding the sweet spot between "all the characters" and "still usable UI" is of course the difficult part. And obviously I'm very biased by the few languages I (more or less) know.  I'll play around with this some more and can create a PR later if you're willing to add another EN keyboard.

If somebody wants to try this layout already, I've just uploaded an apk in [my fork](https://github.com/mpice-mn/thumb-key/releases).

Regarding multitaps: I tried that at first, but it doesn't work well because it would prevent certain letter parings, e.g. if `a` would multitap into `ä`, it would be impossible to actually type `aa`.

**Comment by rootsh0pf** [comment] 2023-05-06 08:54
I just tried the EN-international layout of the fork and that is just what I was talking about, thank you! :)
I would vote for a merge ;)

**Comment by dessalines** [comment] 2023-05-06 19:26
Feel free to open a pull request for an anglo-international keyboard, and I'll add it.

**Comment by dessalines** [comment] 2023-05-21 16:52
I'll close this because swipes and multitaps *can* already do this. All that's necessary is for someone to create keyboards that add the composed letters they wish to have. But those composed letters will apply to specific keyboards, not to all of them universally.

**Closed by dessalines** 2023-05-21 16:52 UTC
Labels: enhancement
