### ISSUE TITLE
Add a way to hide thumb-key to regain screen space

### ISSUE THREAD

**Issue by frederickjh** [dessalines/thumb-key#745] opened 2024-02-20 18:27 UTC
### Describe your suggested feature

I have read through the documentation and cannot seem to find a way to do this, if I somehow missed it please excuse this issue.
There should be a way to hide the thumb-key keyboard. Tapping in a text field makes it appear, but then there seems to be no way to make it hide to regain screen space other than interacting with the app it is entering text on. ie. exit the chat window and come back in. The MessagEase keyboard allows doing this by taping on the hand key

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment] 2024-02-20 21:36
Dupe of #678 

Press the back button to hide any android keyboard.

**Closed by dessalines** 2024-02-20 21:36 UTC

**Comment by frederickjh** [comment] 2024-02-21 06:16
@dessalines Sorry about the duplicate. I forgot to search closed issues. I see that this is the third time in a few weeks that this has come up as an issue. 

It might be a good idea to add the information that using the Android back button will hide the keyboard to the user documentation to avoid further issues being opened about this. My guess is the people moving to Thumb-key from MessagEase are not use to doing it this way, well at least I wasn't.

Thanks for your hard work on Thumb-key!
