### ISSUE TITLE
Add word completion suggestions

### ISSUE THREAD

**Issue by CGenie** [dessalines/thumb-key#149] opened 2023-04-14 10:28 UTC
Hello,

Maybe this is a far-reaching goal, but it would be nice to have suggestions for completing a word. This speeds up typing quite a bit.

There are some resources to get proper word files, e.g. https://freedict.org/.

**Comment by dessalines** [comment] 2023-04-14 15:22
Dupe of #44

**Closed by dessalines** 2023-04-14 15:22 UTC
