### ISSUE TITLE
Layouts from configuration file instead of source code

### ISSUE THREAD

**Issue by maricn** [dessalines/thumb-key#562] opened 2023-11-14 11:54 UTC
- [x] Did you check to see if this issue already exists? (relates to https://github.com/dessalines/thumb-key/issues/234)
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [~] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

**I want to** design a keyboard layout, but doing so I want to change a letter every day in order to find the best possible layout for my personal needs. It is a mixture of four languages, and I can't simply figure out how it will look like. I don't think anyone will want to reuse my design after I finally arrive at it.

**Problem** I'm (and you're) facing is that I would now need to ask you to recompile and publish your project several times each day, polluting the layout set with ever new throwaway layouts.

**Idea** to solve this is to make the layouts configurable so that users can load one from external configuration file.

**Reasoning** is that no configuration should reside in the source code because it increases the time to release, and limits the user experience with regards to speed of release, ability to try out different things, and ability to keep the experiments local.

Ofc, I can fork your project and build and sign the apk with self-signed certificate for my own distribution, but this doesn't help the community, whereas making layouts configurable brings back value and saves time and effort for all users of your app.

Thank you for your amazing work on the app so far, and hope my well meaning feature request will be kindly received. All the best!

**Comment by dessalines** [comment] 2023-11-14 13:07
Dupe of #234

**Closed by dessalines** 2023-11-14 13:07 UTC
Labels: enhancement

**Comment by maricn** [comment] 2023-11-14 15:57
I noticed #234, but you closed the discussion there, and your argument to do so was:
>  But I don't have the time to maintain unchecked keyboards.
I respectfully disagree. With the current setup, you not only need to maintain all kinds of keyboards, but you also need to check them.

If the keyboard layouts would be configurable, you wouldn't need to do either of those. Anyone would be able to make any layout they want, and the responsibility would be on the users to make sure keyboard configs are matching the specification you create. The only maintenance would do would be to pick&choose which of the layouts should be included by default. You could greatly reduce the choice there, and externalize the management of the layouts outside of the keyboard application, so people could download and use whatever layout they want without you having to think about that at all.

You also mentioned in #234 that such configurations would be "unchecked", but that is also solvable by validating the config file. Instead of what you're doing now, including lots of manual work, such validation would be according to the specs, and could be automated.

I'm not asking you to implement this yourself, but you're the project maintainer. I only want to make sure you understand these points and make an informed design decision. I am happy to accept your disagreement. ✌️
